Breaking: rename VaspInputSet.(potcar_functional->user_potcar_functional) and start testing `DictSet` (#3035)
* fix DictSet.as_dict()

* add class DictSetTest with test_as_dict()

* faff

* fix AttributeError: 'MPRelaxSet' object has no attribute 'potcar_functional'

was renamed to user_potcar_functional
on pymatgen/io/vasp/sets.py:123

* skip flaky part of OptimadeTest.test_get_snls_mp()

        if "mp" in extra_fields_single:
>           assert len(structs["mp"]) == len(extra_fields_single["mp"])
E           KeyError: 'mp'

pymatgen/ext/tests/test_optimade.py:54: KeyError

* add Structure.species test (just for peace of mind re #3033)

* add @property potcar_functional to DictSet

* add test for @property potcar_functional

* fix TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'