fix @classmethod and @deprecate order
causing numpy\lib\utils.py:153: in __call__
    old_name = func.__name__
E   AttributeError: 'classmethod' object has no attribute '__name__'