CP2K allow specifying default initial element magmoms (#4170)
* simplify DftSet.create_subsys

* DftSet.create_subsys write element-specific initial magmoms to KIND sections if found in DftSet.element_defaults

* add TestDftSet.test_kind_magnetization for checking different ways of setting element-specific initial magnetization

* fix Section.check failing on missing subsections

AttributeError: 'dict' object has no attribute 'subsections'

* add support for env vars CP2K_DATA_DIR, DEFAULT_CP2K_FUNCTIONAL, DEFAULT_CP2K_BASIS_TYPE, DEFAULT_CP2K_AUX_BASIS_TYPE in addition to PMG_CP2K_DATA_DIR, PMG_DEFAULT_CP2K_FUNCTIONAL, ... config keys

* DftSet add keyword cell: dict[str, Any] | None = None to e.g. specify symmetry

this is useful when running disordered systems with CP2K where enforcing cubic cells minimizes finite size effects

* refactor section keywords merging with section defaults

* readable var names

* remove redundant keywords/subsections or {}

* new DftSet unit test test_cell_parameters

plus type hints

---------

Co-authored-by: Matthew Horton <mkhorton@users.noreply.github.com>