only pin optional deps downwards, leave open upwards
to see if latest boltztrap2 also fails to pip install on windows:

Running setup.py install for BoltzTraP2: finished with status 'error'
  error: subprocess-exited-with-error

  Running setup.py install for BoltzTraP2 did not run successfully.
  exit code: 1

  [80 lines of output]
  running install
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\bandlib.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\dft.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\fd.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\fermisurface.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\fite.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\interface.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\io.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\misc.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\serialization.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\units.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\version.py -> build\lib.win-amd64-3.8\BoltzTraP2
  copying BoltzTraP2\__init__.py -> build\lib.win-amd64-3.8\BoltzTraP2
  creating build\lib.win-amd64-3.8\BoltzTraP2\sphere
  copying BoltzTraP2\sphere\__init__.py -> build\lib.win-amd64-3.8\BoltzTraP2\sphere
  running build_ext
  running build_spglib
  -- Building for: Visual Studio 17 2022
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.

  -- The C compiler identification is MSVC 19.33.31630.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Build type: Release
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/runneradmin/AppData/Local/Temp/pip-install-kyjo84y_/boltztrap2_d6f1b418f4864c838a5adf8988f476d0/external/spglib-1.9.9/build-iwydj5xy
  mingw32-make: *** No targets specified and no makefile found.  Stop.
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-install-kyjo84y_\boltztrap2_d6f1b418f4864c838a5adf8988f476d0\setup.py", line 234, in <module>
      setup(
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\command\install.py", line 545, in run
      self.run_command('build')
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-install-kyjo84y_\boltztrap2_d6f1b418f4864c838a5adf8988f476d0\setup.py", line 184, in run
      self.run_command("build_spglib")
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-install-kyjo84y_\boltztrap2_d6f1b418f4864c838a5adf8988f476d0\setup.py", line 159, in run
      subprocess.check_call(["make"])
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure