fix TypeError: SymmOp.as_xyz_str() missing 1 required positional argument: 'self'
    @classmethod
    @np.deprecate(message="Use as_xyz_str instead")
    def as_xyz_string(cls, *args, **kwargs):  # noqa: D102
>       return cls.as_xyz_str(*args, **kwargs)