Fix CI errors (#2940)
* bump numpy to v1.2.0

* fix new mypy error

* fix typo

* fix CI TypeError

>       state_data = mixing_scheme_no_compat.get_mixing_state_data(ms_scan_only.all_entries, verbose=True)
E       TypeError: MaterialsProjectDFTMixingScheme.get_mixing_state_data() got an unexpected keyword argument 'verbose'

pymatgen/entries/tests/test_mixing_scheme.py:1359: TypeError

* fix find_rings() return type

* fix test order dependence in pymatgen/analysis/tests/test_graphs.py

seems to have been caused by test_edge_editing(), now using deep copy instead in-place edit