ValueError: ASE FixAtoms constraint does not support selective dynamics in only some dimensions. Remove the selective_dynamics=[False, False, False]
ignore mypy assignment error